---

# (1/3) Install the dependencies on your cluster nodes
- hosts: "{{ cluster_name }}"
  become: yes
  name: Configure all the needed stuff
  roles:
    - role: base
      tags: [base]

# (2/3) Initialize your master node
- hosts: "{{ cluster_name }}_master"
  become: true
  pre_tasks:
    - name: Read token from file
      include_vars: cfg/{{ cluster_name }}/token.yml
  roles:
    - role: master
      tags: [master]
