---

- set_fact:
    master_ip_address: "{{ master_ip_address_configured }}"
  when: master_ip_address_configured is defined
  
- set_fact:
    master_ip_address: "{{ ansible_default_ipv4['address'] }}"
  when: master_ip_address_configured is not defined

- name: Save master_ip_address
  shell: "echo master_ip_address{{ ':' }} {{ master_ip_address }} > cfg/{{ cluster_name }}/master_ip_address.yml"
  delegate_to: 127.0.0.1
  become: false

- name: Copy the master configuration
  template:
    src: kubeadm_conf.yaml.j2
    dest: /etc/kubernetes/kubeadm_conf.yaml
  tags:
    - master

- name: Initialize master
  command: kubeadm init --token {{ token }} -config /etc/kubernetes/kubeadm_conf.yaml
  args:
    creates: /etc/kubernetes/pki
  register: master_init
  ignore_errors: true
  tags:
    - master
    - init
