---

- name: stat Tokens
  stat:
    path:  cfg/{{ cluster_name }}_token.yml
  register: file

- include_tasks: retrieve.yml
  when: file.stat.exists

- include_tasks: generate.yml
  when: not file.stat.exists
