---

- name: Assert root partition is expanded
  assert: { that: item.mount != '/' or item.size_total > 10737418240 } # 10 GB
  with_items: '{{ ansible_mounts }}'
  ignore_errors: yes
  register: expanded

- name: Expand partition
  shell: parted /dev/mmcblk0 resizepart 2 15.5GB # NOTE: Assumes 16GB card
  when: expanded|failed
  notify: expand filesystem
