---

- name: Set timezone
  timezone:
    name: Europe/Paris

- include_tasks: essentials.yml
- include_tasks: fs.yml
- include_tasks: docker.yml
- include_tasks: kubernetes.yml
- include_tasks: openfaas.yml
